name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python and uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"

      - name: Check and Test
        run: |
          uv sync --group dev
          make check test
