name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python and uv
        uses: astral-sh/setup-uv@v7

      - name: Run checks
        run: make check

  test:
    needs: check
    uses: ./.github/workflows/test.yml
